### ISSUE TITLE
Allow setting of IBC: ExistingSessionDetectedAction

### ISSUE THREAD

**Issue by kfiroo** [gnzsnz/ib-gateway-docker#142]
## Is your feature request related to a problem? Please describe

In some cases we might want to log into the account manually, this is currently not possible due to the following setting in IBC `config.ini`

```
ExistingSessionDetectedAction=primary
```

## Describe the solution you'd like

Would be nice to control this value via an environment variable

## Describe alternatives you've considered

The current solution (if I understand it correctly) is to override the entire config which feels like an overkill

**Comment by gnzsnz** [comment]
What value you want to use for it?

Your explanation and what ExistingSessionDetectedAction actually do are not aligned.

**Comment by kfiroo** [comment]
Hey, thanks for the quick response 🙏🏼 

Well, as far as I can understand from the docs ([here](https://github.com/gnzsnz/ib-gateway-docker/blob/master/latest/config/ibc/config.ini.tmpl#L296-L329)) there are only 4 valid values here - `primary`, `primaryoverride`, `secondary` and `manual`

I would like to be able to set any of the above

In my specific case I would use `primaryoverride` to allow user sessions to log in and IBC would reconnect when avaliable.

**Comment by gnzsnz** [comment]
ok, i will consider it for the future.

if you feel like sending a pull request go ahead, the change is quite simple, is just a variable on config.ini.tmpl. most of the change in in the documentation.

this will allow to connect outside docker and IBC will not try to reconnect (with the proper settings). other options are to create another account, or to use TWS you connect trough RDP and TWS running in docker

**Comment by gnzsnz** [comment]
merged
