### ISSUE TITLE
10.19.2d is often getting in a weird state during the nightly restarts

### ISSUE THREAD

**Issue by Awnedion** [gnzsnz/ib-gateway-docker#15]
**Describe the bug**
There seems to be two issues that may be related. When the nightly restart/relogin of IBGateway triggers, the phone 2FA can only be done successfully sometimes. The phone alert will trigger but opening it shows an error message before I can attempt to enter my pin (this is not the same error as taking too long to enter the 2FA code).  It seems this may be triggered if I miss the first 2FA login attempt. It keeps triggering every subsequent 2FA alert attempt until a ignore a few of them and then randomly try one later on.

The other issue is that sometimes even if I complete the 2FA successfully, IBGateway will be in a weird state where the VNC server isn't running and client logins to IBGateway don't get results. I seem to need to restart the docker image entirely when this happens. 

**Versions (please complete the following information):**
 - OS: Fedora 36
 - Image Tag (`docker --version`): 10.19.2d

**Comment by gnzsnz** [comment]
Both issues look like upstream issues (ie either IBC or IB gateway issue). Please check IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md#second-factor-authentication). But I think you might be able to set the environment variables in the right way to fix most of it.

could you please share the environment variables that you are using to start up the container? I would need these

- TWOFA_TIMEOUT_ACTION: 
- AUTO_RESTART_TIME: 
- RELOGIN_AFTER_TWOFA_TIMEOUT: 
- TWOFA_EXIT_INTERVAL: 

it's important to set `RELOGIN_AFTER_TWOFA_TIMEOUT=yes`.  Please check IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md#second-factor-authentication)

by the way, you don't need to enter 2FA every day. you can set your variables like this to do it once per week. which will solve 90% of your problems, or at least the "frequency" of your problems

- AUTO_RESTART_TIME: 08:59 AM
- RELOGIN_AFTER_TWOFA_TIMEOUT: "yes"
- TWOFA_EXIT_INTERVAL: "60"
- TWOFA_TIMEOUT_ACTION: restart

I personally use `RELOGIN_AFTER_TWOFA_TIMEOUT=no`  and once per week restart the container.

hope this helps.

**Comment by Awnedion** [comment]
I've been setting config options by mounting a config.ini into the container. This is because of a couple issues: I don't seem to be able to set the 'SecondFactorDevice' property via env variables. Without this set, my phone won't get the 2FA prompt at all. 
The other issue is that the way the env variables pass the account credentials to the process is as command line arguments. These values can be seen by running 'ps -ef' on the server running the container, not too great.

I found that I was using an outdated version of config.ini with all the image version switching I've had to do recently. It was missing one of the 2FA restart options but the container has still been messing up each night even with these extra settings.

Which of the settings that you're using makes the 2FA only been needed once per week? I think the specific restart time would be the only thing my config.ini is missing.

**Comment by gnzsnz** [comment]
the variable you need to set is AUTO_RESTART_TIME, please check IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md#second-factor-authentication).

if you are manually setting config.ini, please don't expect the docker image to work as designed. this is not a "bug".

Regarding user and pass parameters, thanks for pointing it out. I will look at it, I think it can be fixed.

As mentioned on my previous comment this is a problem with IBC usage, please check IBC [documentation](https://github.com/IbcAlpha/IBC/blob/master/userguide.md)
