### ISSUE TITLE
v10.25.1j-latest build fail

### ISSUE THREAD

**Issue by gnzsnz** [gnzsnz/ib-gateway-docker#24]
**Describe the bug**

v10.25.1j-latest build fail

**To Reproduce**
Steps to reproduce the behavior.

launch build action

**Expected behavior**

**Container logs**
If applicable, add the container logs `docker logs <CONTAINER>` or `docker-compose logs` to help explain your problem.

https://github.com/gnzsnz/ib-gateway-docker/actions/runs/6323132757/job/17170258858

https://github.com/gnzsnz/ib-gateway-docker/actions/runs/6323132757/job/17170258858#step:8:334

```
#10 77.29 Archive:  ./IBCLinux-3.18.0.zip
#10 77.29   End-of-central-directory signature not found.  Either this file is not
#10 77.29   a zipfile, or it constitutes one disk of a multi-part archive.  In the
#10 77.29   latter case the central directory and zipfile comment will be found on
#10 77.29   the last disk(s) of this archive.
#10 77.29 unzip:  cannot find zipfile directory in one of ./IBCLinux-3.18.0.zip or
#10 77.29         ./IBCLinux-3.18.0.zip.zip, and cannot find ./IBCLinux-3.18.0.zip.ZIP, period.
```

this can be reproduced on a linux box

```
$ curl -sSOL https://github.com/IbcAlpha/IBC/releases/download/3.18.0/IBCLinux-3.18.0.zip
$ unzip IBCLinux-3.18.0.zip
Archive:  IBCLinux-3.18.0.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of IBCLinux-3.18.0.zip or
        IBCLinux-3.18.0.zip.zip, and cannot find IBCLinux-3.18.0.zip.ZIP, period.
```

**Comment by LACanuck** [comment]
The problem seems to be that IBC changed the path for 3.18.0. It's now https://github.com/IbcAlpha/IBC/releases/download/3.18.0**-Update.1**/IBCLinux-3.18.0.zip. Easy to fix in the Dockerfile. Not sure how best to address this in a generic manner.

**Comment by gnzsnz** [comment]
Yes the problem is to generalize a solution.

I can fix the Dockerfile but will fail on the next release of IBC.

However if the Dockerfile is not fixed every new IB gateway release will fail.
