### ISSUE TITLE
Make IBC AcceptIncomingConnectionAction configurable

### ISSUE THREAD

**Issue by handelsmeisterei** [gnzsnz/ib-gateway-docker#95]
Hey there,
great image! Especially the functionality to run both paper and live in one container saves the day!

Could you please make the IBC setting "AcceptIncomingConnectionAction" configurable via an environment variable?

I currently have to run with custom config and set it there because otherwise TWS does not let me  connect.

Thank you very much!

**Comment by gnzsnz** [comment]
check this, it might help you

https://github.com/gnzsnz/ib-gateway-docker/discussions/74#discussioncomment-8343215

and try the first bullet point
- define TWS_SETTINGS_PATH, and a volume for your settings. then you change that setting through ibgateway/tws gui

for example in `.env`
`TWS_SETTINGS_PATH=/config/tws_settings`

in docker compose
```yml
    volumes:
      - ${PWD}/config:/config
```

this way you can define your settings and store them

![image](https://github.com/gnzsnz/ib-gateway-docker/assets/8376642/4b62b8ef-4d7c-415f-ad75-45a8086b06ec)

this is more secure than what you are asking for.

What you are asking, can be done, it will require a small change. But honestly i don't consider it a priority.

**Comment by gnzsnz** [comment]
included in #117 

next release will include the new codebase and support for `AcceptIncomingConnectionAction`
